export const colors = {
    primaryBlue: '#2563EB',
    primaryBlueDark: '#1D4ED8',
    primaryGreen: '#10B981',
    alertRed: '#EF4444',
    alertOrange: '#F59E0B',
    alertYellow: '#FBBF24',
    background: '#F8FAFC',
    cardBackground: '#FFFFFF',
    textPrimary: '#0F172A',
    textSecondary: '#64748B',
    border: '#E2E8F0',
    successGreen: '#DCFCE7',
    errorRed: '#FEF2F2',
    white: '#FFFFFF',
    lightBlue: '#EFF6FF',
    lightGreen: '#F0FDF4',
    lightOrange: '#FFF7ED',
    lightRed: '#FEF2F2',
    grey100: '#F1F5F9',
    grey300: '#CBD5E1',
};
