export const colors = {
    primaryBlue: '#2D6BE4',
    primaryGreen: '#27AE60',
    alertRed: '#E74C3C',
    alertOrange: '#F39C12',
    alertYellow: '#F1C40F',
    background: '#F8FAFC',
    cardBackground: '#FFFFFF',
    textPrimary: '#1A1A2E',
    textSecondary: '#6B7280',
    border: '#E5E7EB',
    successGreen: '#D1FAE5',
    errorRed: '#FEE2E2',
    white: '#FFFFFF',
    lightBlue: '#F0F4FF',
    lightGreen: '#F0FDF4',
    lightOrange: '#FFF7ED',
    lightRed: '#FEF2F2',
    grey100: '#F3F4F6',
    grey300: '#cccccc',
};
